#####################################################################################################
## Final image
####################################################################################################
FROM intent_brokering_examples:base as base
FROM alpine:latest
ARG APP_NAME
ENV USER_NAME=sample

# Import Chariott user and group from base.
COPY --from=base /etc/passwd /etc/passwd
COPY --from=base /etc/group /etc/group

WORKDIR /sdv
RUN apk update && apk add ca-certificates curl
RUN curl -sSL https://curl.se/ca/cacert.pem > /usr/local/share/ca-certificates/local-ca.crt
RUN update-ca-certificates

# Copy our build
COPY --from=base /sdv/target/x86_64-unknown-linux-musl/release/${APP_NAME} /sdv/${APP_NAME}

# Use the unprivileged chariott user during execution.
USER ${USER_NAME}:${USER_NAME}
ENV APP_NAME=${APP_NAME}
CMD ["sh", "-c", "./${APP_NAME}"]
