name: E2E CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "intent_brokering/common/**"
      - "intent_brokering/ess/**"
      - "intent_brokering/examples/**"
      - "intent_brokering/keyvalue/**"
      - "intent_brokering/proto/**"
      - 'intent_brokering/proto.rs/**'
      - "intent_brokering/src/**"
      - "intent_brokering/tests/**"
      - ".github/workflows/e2e.yaml"
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'rust-toolchain.toml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  CARGO_TERM_COLOR: always
  INTENT_BROKERING_REGISTRY_TTL_SECS: 7

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install protobuf compiler
        run: |
          sudo apt-get update
          sudo apt-get install cmake protobuf-compiler libprotobuf-dev

      - name: Install stable toolchain
        run: rustup show

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Intent Brokering service Container
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.intent_brokering.amd64
          load: true
          tags: intent_brokering:1

      - name: Build KV-App Container
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./intent_brokering/examples/applications/Dockerfile.kv-app.ci
          build-args: APP_NAME=kv-app
          load: true
          tags: kv-app:1

      - name: Start Intent Brokering
        run: |
          docker run -d --name intent_brokering --network host \
            -e RUST_LOG=debug \
            -e INTENT_BROKERING_REGISTRY_TTL_SECS \
            intent_brokering:1

      - name: Start KV-App
        run: |
          docker run -d --name kv-app --network host -e RUST_LOG=debug kv-app:1

      - name: Run E2E tests
        run: |
          cargo test --test "*e2e"

      - name: Print Intent Brokering log output
        if: ${{ always() }}
        run: |
          docker logs intent_brokering > intent_brokering.log
          docker logs intent_brokering

      - name: Archive Intent Brokering log output
        uses: actions/upload-artifact@v1
        with:
          name: Intent Brokering E2E log
          path: intent_brokering.log

      - name: Print KV App log output
        if: ${{ always() }}
        run: |
          docker logs kv-app > kv-app.log
          docker logs kv-app

      - name: Archive KV App log output
        uses: actions/upload-artifact@v1
        with:
          name: KV App E2E log
          path: kv-app.log
